# Generated by Django 5.0.6 on 2024-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_news', '0002_news_original_date_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='news',
            name='original_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
    ]
