# Generated by Django 5.0.6 on 2024-06-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_news', '0003_alter_news_date_alter_news_original_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/news_pictures', verbose_name='Imagen'),
        ),
    ]
