# Generated by Django 5.0.6 on 2024-06-22 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('favorite_game', models.CharField(max_length=30, verbose_name='Juego favorito')),
                ('player_picture', models.ImageField(blank=True, null=True, upload_to='player_picture', verbose_name='Imagen')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre de la mesa:')),
                ('game', models.CharField(max_length=20, verbose_name='Juego:')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('max_players', models.PositiveIntegerField(verbose_name='Cantidad de Jugadores')),
                ('players', models.ManyToManyField(blank=True, related_name='player', to='tables.player')),
            ],
        ),
    ]
