# Generated by Django 5.0.6 on 2024-06-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/player_picture', verbose_name='Imagen'),
        ),
    ]
