# Generated by Django 5.0.6 on 2024-06-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user_id',
        ),
    ]
