# Generated by Django 5.0.6 on 2024-06-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_player_player_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_table',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
