# Generated by Django 5.0.6 on 2024-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_game_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_table',
            name='game',
            field=models.CharField(default=1, max_length=20, verbose_name='Juego:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game_table',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='game_table',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='game_table',
            name='max_players',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Jugadores'),
        ),
        migrations.AlterField(
            model_name='game_table',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre de la mesa:'),
        ),
    ]
